// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivlsawrcootiarfzlbcv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2bHNhd3Jjb290aWFyZnpsYmN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzOTA1MzgsImV4cCI6MjA3NDk2NjUzOH0.bLcw9im3NrSev6AoFdaS3j8ZghHpfq3Zzclk1GkPGeE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});